# Generated by Django 5.2.7 on 2025-12-12 13:15

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, default='client_logos/default.png', null=True, upload_to=customers.models.client_logo_upload_to),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_color',
            field=models.CharField(blank=True, default='#000000', help_text='HEX color code, e.g. #000000', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='secondary_color',
            field=models.CharField(blank=True, default='#000000', help_text='HEX color code, e.g. #000000', max_length=7, null=True),
        ),
    ]
