# Generated by Django 5.2.7 on 2025-11-03 06:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('address', models.CharField()),
                ('customerTpin', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('itemClassCode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('itemTypeCd', models.CharField(blank=True, choices=[('Raw Material', 'Raw Material'), ('Finished Product', 'Finished Product'), ('Service', 'Service')], max_length=20, null=True)),
                ('itemOrigin', models.CharField(max_length=100)),
                ('pkgUnitCd', models.CharField(max_length=50)),
                ('qtyUnitCd', models.CharField(max_length=50)),
                ('vatCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('iplCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('tlCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('exciseTxCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStockMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_qty', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_masters', to='base.iteminfo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemstockmaster_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('use_yn', models.CharField(choices=[('Y', 'Used'), ('N', 'Unused')], default='Y', max_length=1, verbose_name='Active Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=13)),
                ('prc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sply_amt', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('taxbl_amt', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('vat_cat_cd', models.CharField(max_length=5)),
                ('tax_amt', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('tot_amt', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockitemdetail_created', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='base.iteminfo')),
            ],
        ),
    ]
