# Generated by Django 5.2.7 on 2025-11-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='stock_item',
            new_name='item',
        ),
    ]
