# Generated by Django 5.2.7 on 2025-11-02 19:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customerinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('itemClassCode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('itemOrigin', models.CharField(max_length=100)),
                ('pkgUnitCd', models.CharField(max_length=50)),
                ('qtyUnitCd', models.CharField(max_length=50)),
                ('vatCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('iplCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('tlCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('exciseTxCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
