# Generated by Django 5.2.7 on 2025-11-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_iteminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminfo',
            name='itemTypeCd',
            field=models.CharField(blank=True, choices=[('GOODS', 'Goods'), ('SERVICES', 'Services'), ('DIGITAL', 'Digital Products')], max_length=20, null=True),
        ),
    ]
