# Generated by Django 5.2.7 on 2025-11-26 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_supplier_created_by_alter_supplier_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpin', models.CharField(max_length=20)),
                ('bhf_id', models.CharField(max_length=10)),
                ('org_invc_no', models.IntegerField()),
                ('cis_invc_no', models.CharField(max_length=50)),
                ('cust_tpin', models.CharField(blank=True, max_length=20, null=True)),
                ('cust_nm', models.CharField(max_length=255)),
                ('sales_ty_cd', models.CharField(max_length=5)),
                ('rcpt_ty_cd', models.CharField(max_length=5)),
                ('pmt_ty_cd', models.CharField(max_length=5)),
                ('sales_stts_cd', models.CharField(max_length=5)),
                ('cfm_dt', models.CharField(max_length=20)),
                ('sales_dt', models.CharField(max_length=10)),
                ('tot_item_cnt', models.IntegerField()),
                ('tot_taxbl_amt', models.FloatField()),
                ('tot_tax_amt', models.FloatField()),
                ('tot_amt', models.FloatField()),
                ('result_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('result_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('result_dt', models.CharField(blank=True, max_length=20, null=True)),
                ('rcpt_no', models.IntegerField(blank=True, null=True)),
                ('intrl_data', models.CharField(blank=True, max_length=100, null=True)),
                ('rcpt_sign', models.CharField(blank=True, max_length=50, null=True)),
                ('vsdc_rcpt_pbct_date', models.CharField(blank=True, max_length=20, null=True)),
                ('sdc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('mrc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('prc', models.FloatField()),
                ('sply_amt', models.FloatField()),
                ('vat_taxbl_amt', models.FloatField()),
                ('vat_amt', models.FloatField()),
                ('ipl_taxbl_amt', models.FloatField(default=0.0)),
                ('ipl_amt', models.FloatField(default=0.0)),
                ('tl_taxbl_amt', models.FloatField(default=0.0)),
                ('tl_amt', models.FloatField(default=0.0)),
                ('ecm_taxbl_amt', models.FloatField(default=0.0)),
                ('ecm_amt', models.FloatField(default=0.0)),
                ('tot_amt', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.iteminfo')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.sale')),
            ],
        ),
    ]
