# Generated by Django 5.2.7 on 2025-11-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_iteminfo_itemtypecd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='itemTypeCd',
            field=models.CharField(blank=True, choices=[('Raw Material', 'Raw Material'), ('Finished Product', 'Finished Product'), ('Service', 'Service')], max_length=20, null=True),
        ),
    ]
