# Generated by Django 5.2.7 on 2025-11-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_sale_saleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='bhf_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='intrl_data',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='mrc_no',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='rcpt_sign',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='result_cd',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='result_dt',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='result_msg',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tpin',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='vsdc_rcpt_pbct_date',
        ),
    ]
