# Generated by Django 5.2.7 on 2025-11-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_sale_bhf_id_remove_sale_intrl_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='generatedInvoiceUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
