# Generated by Django 5.2.7 on 2025-11-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_sale_generatedinvoiceurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='generatedInvoiceUrl',
        ),
        migrations.AddField(
            model_name='sale',
            name='generated_invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/%d/'),
        ),
    ]
