# Generated by Django 5.2.7 on 2025-12-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_itemstockmaster_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cisInvcNo', models.CharField(max_length=50)),
                ('orgInvcNo', models.IntegerField()),
                ('spplrTpin', models.CharField(max_length=20)),
                ('spplrBhfId', models.CharField(max_length=10)),
                ('spplrNm', models.CharField(max_length=255)),
                ('spplrInvcNo', models.CharField(max_length=50)),
                ('regTyCd', models.CharField(max_length=5)),
                ('pchsTyCd', models.CharField(max_length=5)),
                ('rcptTyCd', models.CharField(max_length=5)),
                ('pmtTyCd', models.CharField(max_length=5)),
                ('pchsSttsCd', models.CharField(max_length=5)),
                ('cfmDt', models.CharField(max_length=20)),
                ('pchsDt', models.CharField(max_length=20)),
                ('cnclReqDt', models.CharField(blank=True, max_length=20)),
                ('cnclDt', models.CharField(blank=True, max_length=20)),
                ('totItemCnt', models.IntegerField()),
                ('totTaxblAmt', models.DecimalField(decimal_places=4, max_digits=18)),
                ('totTaxAmt', models.DecimalField(decimal_places=4, max_digits=18)),
                ('totAmt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remark', models.TextField(blank=True)),
                ('regrNm', models.CharField(max_length=255)),
                ('regrId', models.CharField(max_length=255)),
                ('modrNm', models.CharField(max_length=255)),
                ('modrId', models.CharField(max_length=255)),
            ],
        ),
    ]
