# Generated by Django 5.2.7 on 2025-12-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemSeq', models.IntegerField()),
                ('itemCd', models.CharField(max_length=50)),
                ('itemClsCd', models.CharField(max_length=50)),
                ('itemNm', models.CharField(max_length=255)),
                ('bcd', models.CharField(blank=True, max_length=100, null=True)),
                ('pkgUnitCd', models.CharField(max_length=10)),
                ('pkg', models.DecimalField(decimal_places=2, max_digits=18)),
                ('qtyUnitCd', models.CharField(max_length=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('prc', models.DecimalField(decimal_places=2, max_digits=18)),
                ('splyAmt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('dcRt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dcAmt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('taxTyCd', models.CharField(max_length=5)),
                ('taxblAmt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vatCatCd', models.CharField(max_length=5)),
                ('taxAmt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('totAmt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('iplCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('tlCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('exciseCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('iplTaxblAmt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tlTaxblAmt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('exciseTaxblAmt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('iplAmt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tlAmt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('exciseTxAmt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.purchase')),
            ],
        ),
    ]
