# Generated by Django 5.2.7 on 2025-12-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_quotation_quotationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='customerTpin',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
